// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace lol.dataloader
{
    [Table("champion", Schema = "lol")]
    public partial class Champion
    {
        [Key]
        [Column("champion_id")]
        public int ChampionId { get; set; }
        [Column("riot_champion_id")]
        public int RiotChampionId { get; set; }
        [Required]
        [Column("name")]
        [StringLength(255)]
        public string Name { get; set; }
    }
}