// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace lol.dataloader
{
    [Table("match", Schema = "lol")]
    public partial class Match
    {
        [Key]
        [Column("match_id")]
        public int MatchId { get; set; }
        [Column("riot_match_id")]
        public long RiotMatchId { get; set; }
        [Column("game_duration_in_seconds")]
        public long GameDurationInSeconds { get; set; }
        [Column("season")]
        public int? Season { get; set; }
        [Column("queue_type")]
        public int? QueueType { get; set; }
        [Column("game_version")]
        public string GameVersion { get; set; }
    }
}