// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace lol.dataloader
{
    [Table("match", Schema = "lol")]
    public partial class Match
    {
        [Key]
        public int MatchId { get; set; }
        public long RiotMatchId { get; set; }
        public long GameDurationInSeconds { get; set; }
    }
}