// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace lol.dataloader
{
    public partial class MovietimeContext : DbContext
    {
        public MovietimeContext()
        {
        }

        public MovietimeContext(DbContextOptions<MovietimeContext> options)
            : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseSqlServer("Data Source=thedinks.database.windows.net;Initial Catalog=MovieTime;Persist Security Info=True;User ID=dinkadmin;Password=Sadtoilet2;Pooling=False;MultipleActiveResultSets=False;Connect Timeout=60;Encrypt=True;TrustServerCertificate=False");
        }

        public virtual DbSet<Champion> Champion { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<MatchParticipant> MatchParticipant { get; set; }
        public virtual DbSet<Summoner> Summoner { get; set; }
        public virtual DbSet<TeamBans> TeamBans { get; set; }
        public virtual DbSet<TeamStats> TeamStats { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TeamBans>(entity =>
            {
                entity.HasKey(e => e.TeamBanId)
                    .HasName("PK__team_ban__872A745308440CFF");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}