// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace lol.dataloader
{
    [Table("team_bans", Schema = "lol")]
    public partial class TeamBans
    {
        [Key]
        [Column("team_ban_id")]
        public int TeamBanId { get; set; }
        [Column("champion_id")]
        public int ChampionId { get; set; }
        [Column("pick_turn")]
        public int PickTurn { get; set; }
    }
}